baseURL = "http://www.rico.ai/"
languageCode = "en-us"
title = "rico.ai"
paginate = 5
paginatepath = "content/posts"
pluralizelisttitles = false
DisqusShortname = "YOUR_SHORT_NAME_HERE"
Copyright = "All rights reserved - 2017"
canonifyurls = true
theme = "casper"

[params]
  description = "Lets see some AI"
  metadescription = "Used as 'description' meta tag for both home and index pages. If not set, 'description' will be used instead"
  cover = "images/cover.jpg"
  author = "Rico Castelo"
  authorlocation = "San Diego, California"
  authorwebsite = "http://www.rico.ai"
  authorbio= "AI from Rico Castelo"
  logo = "images/logo.png"
  googleAnalyticsUserID = "UA-79101-12"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = "http://feeds.feedburner.com/..."
  githubName = "ricoai"
  twitterName = "rico_deep_ai"
  # facebookName = ""
  # codepenName = ""
  # linkedinName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = true
[permalinks]
post = "/:slug/"
[sitemap]
ChangeFreq = ""
Filename = "sitemap.xml"
Priority = "-1"

  # Setting a value will load highlight.js and enable syntax highlighting using the style selected.
  # See https://github.com/isagalaev/highlight.js/tree/master/src/styles for available styles
  # A preview of above styles can be viewed at https://highlightjs.org/static/demo/
  hjsStyle = "default"

  [params.social]
    twitter = "rico_deep_ai"

  [[menu.main]]
  name = "My Blog"
  weight = -120
  identifier = "blog"
  url = "/"

[[menu.main]]
name = "Github repos"
pre = "<h3>Follow me</h3>"
url = "https://github.com/ricoai"
weight = 100